apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    spec:
      containers:
        - name: qr-api
          image: ivangalindo/devops-qr-code-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: AWS_S3_BUCKET
              value: "qrcode-storage-ivangalindo-capstone"
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret
                  key: AWS_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: qr-api-service
spec:
  type: ClusterIP
  selector:
    app: qr-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
